backend/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter  # , SimpleRouter
from .views import CategoryCourseViewSet, CourseViewSet, ScUserViewSet
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

router = DefaultRouter()  # добавляет вывод /api/ с markdown
# router = SimpleRouter() # ничего не добавляет
router.register('category', CategoryCourseViewSet, basename='category')
router.register('course', CourseViewSet, basename='course')
router.register('user', ScUserViewSet, basename='user')
# router.register('category/<int:pk>', CategoryCourseViewSet, basename='model')
# router.register('course', CourseViewSet)                     # 1 вариант
# router.register('course', CourseViewSet, basename='model')   # 2 вариант
# # 3 вариант
# router.register('auth-token', CustomAuthToken.as_view(), basename='model')


app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

# urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from graphene_django.views import GraphQLView

handler403 = 'mainapp.views.error_403'
handler404 = 'mainapp.views.error_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('userapp.urls')),
    path('', include('mainapp.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    path("graphql/", GraphQLView.as_view(graphiql=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

backend/userapp/urls.py
from django.urls import path
from . import views

app_name = 'userapp'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout'),
    path('registration/', views.UserRegisterView.as_view(), name='registration'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('changepassword/', views.UserPasswordChangeForm.as_view(), name='changepassword'),
    path('', views.index_view, name='index'),
]

backend/templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js h-100">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <title>СуперШкола:
    {% block title %}
      Главная
    {% endblock %}
  </title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.png' %}" />
  <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}" alt="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/superschool.css' %}">
</head>
<body class="d-flex flex-column h-100">
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'mainapp:index' %}">
        <img src="{% static 'images/favicon.png' %}" alt="" width="30" height="24">
        СуперШкола</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="{% url 'mainapp:index' %}">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if '/categorycourse/' in request.path %}active{% endif %}" href="{% url 'mainapp:categorycourse_list' %}">Направления</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link {% if '/course/' in request.path %}active{% endif %}" href="{% url 'mainapp:course_list' %}">Курсы</a>
          </li> 
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if '/myedu/' in request.path %}active{% endif %}" href="{% url 'mainapp:myedu_list' %}">Обучение</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link {% if '/contacts/' in request.path %}active{% endif %}" href="{% url 'mainapp:contacts' %}">Контакты</a>
          </li>
        </ul>
      </div>
        {% if user.is_authenticated %}
        <div class="input-group"></div>
        <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
          aria-expanded="false">{{ user.get_lastname }}</button>
        <ul class="dropdown-menu dropdown-menu-end">
          <li><a class="dropdown-item" href="{% url 'userapp:profile' %}">Профиль</a></li>
          <li><a class="dropdown-item" href="{% url 'mainapp:myedu_list' %}">Обучение</a></li>
          <li><a class="dropdown-item" href="#">Something else here</a></li>
          <li><hr class="dropdown-divider"></li>
          <li>
            <form action="{% url 'userapp:logout' %}" method="post">
              {% csrf_token %}
              <button class="dropdown-item" type="submit">Выход</button>
            </form>
          </li>
        </ul>
        </div>
        {% else %}
        <div>
          <a class="btn btn-outline-primary" href="{% url 'userapp:login' %}">Вход</a>
        </div>
        {% endif %}
    </div>
  </nav>
  {% block body %}
  {% endblock %}
  <footer
    class="footer mt-auto py-3 bg-dark d-flex flex-wrap justify-content-between align-items-center py-3 px-3 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="#" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <img src="{% static 'images/favicon.png' %}" class="bi" width="30" height="24">
      </a>
      <span class="mb-3 mb-md-0 text-muted">&copy; 2023г. СуперШкола</span>
    </div>
    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a class="nav-link px-2 text-muted" target="_blank"
          href="https://github.com/Mistrikov/otus_hw_07"><i class="bi bi-github"></i></a></li>
    </ul>
  </footer>
  <script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
{% block scripts %}
{% endblock %}
</html>