backend/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter  # , SimpleRouter
from .views import CategoryCourseViewSet, CourseViewSet, ScUserViewSet
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

router = DefaultRouter()  # добавляет вывод /api/ с markdown
# router = SimpleRouter() # ничего не добавляет
router.register('category', CategoryCourseViewSet, basename='category')
router.register('course', CourseViewSet, basename='course')
router.register('user', ScUserViewSet, basename='user')
# router.register('category/<int:pk>', CategoryCourseViewSet, basename='model')
# router.register('course', CourseViewSet)                     # 1 вариант
# router.register('course', CourseViewSet, basename='model')   # 2 вариант
# # 3 вариант
# router.register('auth-token', CustomAuthToken.as_view(), basename='model')


app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

# urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from graphene_django.views import GraphQLView

handler403 = 'mainapp.views.error_403'
handler404 = 'mainapp.views.error_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('userapp.urls')),
    path('', include('mainapp.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    path("graphql/", GraphQLView.as_view(graphiql=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

backend/userapp/urls.py
from django.urls import path
from . import views

app_name = 'userapp'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout'),
    path('registration/', views.UserRegisterView.as_view(), name='registration'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('changepassword/', views.UserPasswordChangeForm.as_view(), name='changepassword'),
    path('', views.index_view, name='index'),
]

backend/userapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


def user_directory_path(instance, filename):
    # Путь для сохранения персональных файлов MEDIA_ROOT / user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.id, filename)


class ScUser(AbstractUser):
    email = models.EmailField(unique=True)
    phone = models.TextField(unique=False, null=True, default='')
    photo = models.ImageField(upload_to=user_directory_path, blank=True, null=True, verbose_name="Фотография")

    def get_lastname(self):
        return self.last_name

    def get_mediapath(self):
        return self.id

backend/userapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
# from django.contrib.auth import authenticate, login
# from image_uploader_widget.widgets import ImageUploaderWidget


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label="Логин",
                widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label="Пароль",
                widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': "Имя",
            'last_name': "Фамилия",
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))
    photo = forms.ImageField(label='Фото', widget=forms.FileInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

backend/userapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, get_user_model
from .forms import ProfileUserForm, LoginUserForm, UserRegisterForm, UserPasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView, UpdateView
from django.conf import settings


def index_view(request):
    return render(request, 'userapp/index.html')


class LogoutUser(LogoutView):
    success_url = reverse_lazy('mainapp:categorycourse_list')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'userapp/login.html'
    success_url = reverse_lazy('mainapp:categorycourse_list')


class UserRegisterView(CreateView):
    form_class = UserRegisterForm
    success_url = reverse_lazy('userapp:profile')
    template_name = 'userapp/register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
        if user is not None:
            login(request=self.request, user=user)
        return response


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'userapp/profile.html'
    extra_context = {
        'title': "Профиль пользователя",
        'default_image': settings.DEFAULT_USER_IMAGE,
    }

    def get_success_url(self):
        return reverse_lazy('userapp:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChangeForm(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserPasswordChangeForm
    template_name = 'userapp/profile.html'

backend/userapp/templates/userapp/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}
СуперШкола
{% endblock %}

{% block body %}
{% if form.errors %}
<div class="alert alert-danger d-flex">
  <i class="bi bi-exclamation-triangle-fill ">
    Неверные логин или пароль. Попробуйте еще раз
  </i>
</div>
{% endif %}

{% if next %}
{% if user.is_authenticated %}
<div class="alert alert-danger d-flex">
  <i class="bi bi-exclamation-triangle-fill ">
    Вы не можете просматривать эту страницу. Недостаточно прав
  </i>
</div>
{% else %}
<div class="alert alert-danger d-flex">
  <i class="bi bi-exclamation-triangle-fill ">
    Для просмотра этой страницы войдите на сайт
  </i>
</div>
{% endif %}
{% endif %}

<form method="post" action="{% url 'userapp:login' %}">
  {% csrf_token %}
  <div class="text-center bg-body-tertiary rounded-3">
    <img src="{% static 'images/logo.png' %}" class="bi mt-4 mb-3" width="100" height="100">
    <h1 class="text-body-emphasis">Вход в СуперШколу</h1>
    <table class="col-lg-4 mx-auto fs-5 text-muted">
      <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
      </tr>
      <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
      </tr>
    </table>
    <p></p>
    <div class="d-inline-flex gap-2 mb-5">
      <input class="btn btn-primary btn-sm px-4 rounded-pill" type="submit" value="Войти" />
      <a class="btn btn-outline-secondary btn-sm px-4 rounded-pill"
        href="{% url 'userapp:registration' %}">Регистрация</a>
      <a class="btn btn-outline-secondary btn-sm px-4 rounded-pill" href="/">Отмена</a>
    </div>
    <p><a href="#">Забыли пароль?</a></p>
  </div>
  <input type="hidden" name="next" value="{{ next }}" />
</form>
{% endblock %}

backend/userapp/templates/userapp/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль успешно изменен!</h1>

<p>Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

backend/userapp/templates/userapp/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Изменение пароля</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Изменить пароль</button></p>
</form>

{% endblock %}

backend/userapp/templates/userapp/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}
СуперШкола
{% endblock %}

{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="text-center bg-body-tertiary rounded-3">
        <h2 class="text-body-emphasis">Профиль</h2>
          <table class="col-lg-4 mx-auto fs-5 text-muted">
            {% for field in form.visible_fields %}
            <tr>
                <td>{{ field.label_tag }}</td>
                <td>
                    {% if field.name == 'photo' %}
                        {% if user.photo %}
                            <p><img src="{{user.photo.url}}" width="100"></p>
                        {% else %}
                            <p><img src="{{ default_image }}"></p>
                        {% endif %}
                    {% endif %}
                    {{ field }}</td>
  
            </tr>
                {% if field.errors %}
                <tr><td colspan="2">
                    {{ field.errors }}
                </td></tr>
                {% endif %}
            {% endfor %}
            </table>
            <p></p>
        <div class="d-inline-flex gap-2 mb-5">
          <input class="btn btn-primary btn-sm px-4 rounded-pill" type="submit" value="Обновить" />
          <a class="btn btn-secondary btn-sm px-4 rounded-pill" href="{% url 'mainapp:myedu_list' %}">Мои курсы</a>
          <a class="btn btn-outline-secondary btn-sm px-4 rounded-pill" href="{% url 'userapp:changepassword' %}">Изменить пароль</a>
          <a class="btn btn-outline-secondary btn-sm px-4 rounded-pill" href="/">Отмена</a>
        </div>
      </div>
</form>
{% endblock %}

backend/userapp/templates/userapp/register.html
{% extends "base.html" %}
{% load static %}

{% block title %}
СуперШкола
{% endblock %}

{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="text-center bg-body-tertiary rounded-3">
        <h2 class="text-body-emphasis">Регистрация</h2>
          <table class="col-lg-4 mx-auto fs-5 text-muted">
            {% for field in form.visible_fields %}
            <tr>
                <td>{{ field.label_tag }}</td>
                <td>{{ field }}</td>
            </tr>
                {% if field.errors %}
                <tr><td colspan="2">
                    {{ field.errors }}
                </td></tr>
                {% endif %}
            {% endfor %}
            </table>
            <p></p>
        <div class="d-inline-flex gap-2 mb-5">
          <input class="btn btn-primary btn-sm px-4 rounded-pill" type="submit" value="Зарегистрироваться" />
          <a class="btn btn-outline-secondary btn-sm px-4 rounded-pill" href="/">Отмена</a>
        </div>
      </div>
    </form>
{% endblock %}

backend/userapp/templates/userapp/register_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Добро пожаловать!</h1>

<p>Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по этой
  <a href="{% url 'users:login' %}">ссылке</a>
</p>
{% endblock %}